# -*- coding: utf-8 -*-
"""
Created on Fri Mar 24 14:26:50 2023

@author: Joe Tan
"""


def get_region_lst():
    region_dict = {
        'AFG': 'Afghanistan',
        'ALB': 'Albania',
        'DZA': 'Algeria',
        'ASM': 'American_Samoa',
        'AND': 'Andorra',
        'AGO': 'Angola',
        'AIA': 'Anguilla',
        'ATA': 'Antarctica',
        'ATG': 'Antigua_and_Barbuda',
        'ARG': 'Argentina',
        'ARM': 'Armenia',
        'ABW': 'Aruba',
        'AUS': 'Australia',
        'AUT': 'Austria',
        'AZE': 'Azerbaijan',
        'BHS': 'Bahamas',
        'BHR': 'Bahrain',
        'BGD': 'Bangladesh',
        'BRB': 'Barbados',
        'BLR': 'Belarus',
        'BEL': 'Belgium',
        'BLZ': 'Belize',
        'BEN': 'Benin',
        'BMU': 'Bermuda',
        'BTN': 'Bhutan',
        'BOL': 'Bolivia',
        'BIH': 'Bosnia_and_Herzegovina',
        'BWA': 'Botswana',
        'BVT': 'Bouvet_Island',
        'BRA': 'Brazil',
        'IOT': 'British_Indian_Ocean_Territory',
        'BRN': 'Brunei_Darussalam',
        'BGR': 'Bulgaria',
        'BFA': 'Burkina_Faso',
        'BDI': 'Burundi',
        'CPV': 'Cape_Verde',
        'KHM': 'Cambodia',
        'CMR': 'Cameroon',
        'CAN': 'Canada',
        'CYM': 'Cayman_Islands',
        'CAF': 'Central_African_Republic',
        'TCD': 'Chad',
        'CHL': 'Chile',
        'MAC': 'Macao',
        'HKG': 'Hong_Kong',
        'CHN': 'China',
        'CXR': 'Christmas_Island',
        'CCK': 'Cocos_Islands',
        'COL': 'Colombia',
        'COM': 'Comoros',
        'COD': 'Democratic_Republic_of_the_Congo',
        'COG': 'Republic_of_Congo',
        'COK': 'Cook_Islands',
        'CRI': 'Costa_Rica',
        'HRV': 'Croatia',
        'CUB': 'Cuba',
        'CUW': 'Curaçao',
        'CYP': 'Cyprus',
        'CZE': 'Czech_Republic',
        'CIV': "Ivoire", # Côte_d'Ivoire
        'DNK': 'Denmark',
        'DJI': 'Djibouti',
        'DOM': 'Dominican_Republic',
        'DMA': 'Dominica',
        'ECU': 'Ecuador',
        'EGY': 'Egypt',
        'SLV': 'El_Salvador',
        'GNQ': 'Equatorial_Guinea',
        'PNG': 'Papua_New_Guinea',
        'ERI': 'Eritrea',
        'EST': 'Estonia',
        'SWZ': 'Eswatini', # Used to be called as Kingdom_of_Swaziland
        'ETH': 'Ethiopia',
        'FLK': 'Falkland_Islands',
        'FRO': 'Faroe_Islands',
        'FJI': 'Fiji',
        'FIN': 'Finland',
        'FRA': 'France',
        'GUF': 'French_Guiana',
        'PYF': 'French_Polynesia',
        'ATF': 'French_Southern_Territories',
        'GAB': 'Gabon',
        'GMB': 'Gambia',
        'GEO': 'Georgia',
        'DEU': 'Germany',
        'GHA': 'Ghana',
        'GIB': 'Gibraltar',
        'GRC': 'Greece',
        'GRL': 'Greenland',
        'GRD': 'Grenada',
        'GLP': 'Guadeloupe',
        'GUM': 'Guam',
        'GTM': 'Guatemala',
        'GGY': 'Guernsey',
        'GNB': 'Guinea-Bissau',
        'GIN': 'Guinea',
        'GUY': 'Guyana',
        'HTI': 'Haiti',
        'HMD': 'Heard_Island_and_McDonald_Islands',
        'VAT': 'Holy_See',
        'HND': 'Honduras',
        'HKG': 'Hong_Kong',
        'HUN': 'Hungary',
        'ISL': 'Iceland',
        'IND': 'India',
        'IDN': 'Indonesia',
        'IRN': 'Iran',
        'IRQ': 'Iraq',
        'IRL': 'Ireland',
        'IMN': 'Isle_of_Man',
        'ISR': 'Israel',
        'ITA': 'Italy',
        'JAM': 'Jamaica',
        'JPN': 'Japan',
        'JEY': 'Jersey',
        'JOR': 'Jordan',
        'KAZ': 'Kazakhstan',
        'KEN': 'Kenya',
        'KIR': 'Kiribati',
        'PRK': "Democratic_People's_Republic_of_Korea",
        'KOR': 'Republic_of_Korea',
        'KOS': "Republic_of_Kosovo",
        'KWT': 'Kuwait',
        'KGZ': 'Kyrgyz_Republic',
        'LAO': "Lao",
        'LVA': 'Latvia',
        'LBN': 'Lebanon',
        'LSO': 'Lesotho',
        'LBR': 'Liberia',
        'LBY': 'Libya',
        'LIE': 'Liechtenstein',
        'LTU': 'Lithuania',
        'LUX': 'Luxembourg',
        'MDG': 'Madagascar',
        'MWI': 'Malawi',
        'MYS': 'Malaysia',
        'MDV': 'Maldives',
        'MLI': 'Mali',
        'MLT': 'Malta',
        'MHL': 'Marshall_Islands',
        'MTQ': 'Martinique',
        'MRT': 'Mauritania',
        'MUS': 'Mauritius',
        'MYT': 'Mayotte',
        'MEX': 'Mexico',
        'FSM': 'Micronesia',
        'MDA': 'Moldova',
        'MCO': 'Monaco',
        'MNG': 'Mongolia',
        'MNE': 'Montenegro',
        'MSR': 'Montserrat',
        'MAR': 'Morocco',
        'MOZ': 'Mozambique',
        'MMR': 'Myanmar',
        'NAM': 'Namibia',
        'NRU': 'Nauru',
        'NPL': 'Nepal',
        'NLD': 'Netherlands',
        'NCL': 'New_Caledonia',
        'NZL': 'New_Zealand',
        'NIC': 'Nicaragua',
        'NGA': 'Nigeria',
        'NER': 'Niger',
        'NIU': 'Niue',
        'NFK': 'Norfolk_Island',
        'MNP': 'Northern_Mariana_Islands',
        'NOR': 'Norway',
        'OMN': 'Oman',
        'PAK': 'Pakistan',
        'PLW': 'Palau',
        'PAN': 'Panama',
        'PRY': 'Paraguay',
        'PER': 'Peru',
        'PHL': 'Philippines',
        'PCN': 'Pitcairn',
        'POL': 'Poland',
        'PRT': 'Portugal',
        'PRI': 'Puerto_Rico',
        'QAT': 'Qatar',
        'MKD': 'Macedonia', # Republic_of_North_Macedonia or Former_Yugoslav_Republic_of_Macedonia
        'ROU': 'Romania',
        'RUS': 'Russian_Federation',
        'RWA': 'Rwanda',
        'REU': 'Réunion',
        'BLM': 'Barthélemy',
        'KNA': 'Kitts_and_Nevis',
        'LCA': 'Lucia',
        'MAF': 'Martin',
        'SPM': 'Pierre_and_Miquelon',
        'VCT': 'Vincent_and_the_Grenadines',
        'WSM': 'Samoa',
        'SMR': 'San_Marino',
        'STP': 'São_Tomé_and_Príncipe',
        'SAU': 'Saudi_Arabia',
        'SEN': 'Senegal',
        'SRB': 'Serbia',
        'SYC': 'Seychelles',
        'SLE': 'Sierra_Leone',
        'SGP': 'Singapore',
        'SXM': 'Sint_Maarten',
        'SVK': 'Slovak_Republic',
        'SVN': 'Slovenia',
        'SLB': 'Solomon_Islands',
        'SOM': 'Somalia',
        'ZAF': 'South_Africa',
        'SGS': 'South_Georgia_and_the_South_Sandwich_Islands',
        'SSD': 'South_Sudan',
        'ESP': 'Spain',
        'LKA': 'Sri_Lanka',
        'SDN': 'Sudan',
        'SUR': 'Suriname',
        'SJM': 'Svalbard_and_Jan_Mayen',
        'SWE': 'Sweden',
        'CHE': 'Switzerland',
        'SYR': 'Syrian_Arab_Republic',
        'TZA': 'Tanzania',
        'TWN': 'Taiwan',
        'TJK': 'Tajikistan',
        'THA': 'Thailand',
        'TLS': 'Timor-Leste',
        'TGO': 'Togo',
        'TKL': 'Tokelau',
        'TON': 'Tonga',
        'TTO': 'Trinidad_and_Tobago',
        'TUN': 'Tunisia',
        'TUR': 'Turkey',
        'TKM': 'Turkmenistan',
        'TCA': 'Turks_and_Caicos_Islands',
        'TUV': 'Tuvalu',
        'UGA': 'Uganda',
        'UKR': 'Ukraine',
        'ARE': 'United_Arab_Emirates',
        'GBR': 'United_Kingdom',
        'UMI': 'United_States_Minor_Outlying_Islands',
        'USA': 'United_States',
        'URY': 'Uruguay',
        'UZB': 'Uzbekistan',
        'VUT': 'Vanuatu',
        'VEN': 'Venezuela',
        'VNM': 'Vietnam',
        'VGB': 'Virgin_Islands_British',
        'VIR': 'Virgin_Islands_U.S.',
        'WLF': 'Wallis_and_Futuna',
        'ESH': 'Western_Sahara',
        'YEM': 'Yemen',
        'ZMB': 'Zambia',
        'ZWE': 'Zimbabwe',
        'ALA': 'Åland_Islands'
    }
    
    return region_dict



# def get_region_lst():
#     region_dict = {
#         'AFG': 'Afghanistan',
#         'ALB': 'Albania',
#         'DZA': 'Algeria',
#         'AGO': 'Angola',
#         'ATG': 'Antigua_and_Barbuda',
#         'ARG': 'Argentina',
#         'ARM': 'Armenia',
#         'AUS': 'Australia',
#         'AUT': 'Austria',
#         'AZE': 'Azerbaijan',
#         'BHS': 'Bahamas',
#         'BHR': 'Bahrain',
#         'BGD': 'Bangladesh',
#         'BRB': 'Barbados',
#         'BLR': 'Belarus',
#         'BEL': 'Belgium',
#         'BLZ': 'Belize',
#         'BEN': 'Benin',
#         'BMU': 'Bermuda',
#         'BTN': 'Bhutan',
#         'BOL': 'Bolivia',
#         'BIH': 'Bosnia_and_Herzegovina',
#         'BWA': 'Botswana',
#         'BRA': 'Brazil',
#         'BRN': 'Brunei_Darussalam',
#         'BGR': 'Bulgaria',
#         'BFA': 'Burkina_Faso',
#         'BDI': 'Burundi',
#         'CPV': 'Cabo_Verde',
#         'KHM': 'Cambodia',
#         'CMR': 'Cameroon',
#         'CAN': 'Canada',
#         'CAF': 'Central_African_Republic',
#         'TCD': 'Chad',
#         'CHL': 'Chile',
#         'CHN': 'China',
#         'COL': 'Colombia',
#         'COM': 'Comoros',
#         'COG': 'Republic_of_the_Congo',
#         'COD': 'Democratic_Republic_of_the_Congo',
#         'CRI': 'Costa_Rica',
#         'CIV': "Côte_d'Ivoire",
#         'HRV': 'Croatia',
#         'CUB': 'Cuba',
#         'CYP': 'Cyprus',
#         'CZE': 'Czech_Republic',
#         'DNK': 'Denmark',
#         'DJI': 'Djibouti',
#         'DMA': 'Dominica',
#         'DOM': 'Dominican_Republic',
#         'ECU': 'Ecuador',
#         'EGY': 'Egypt',
#         'SLV': 'El_Salvador',
#         'GNQ': 'Equatorial_Guinea',
#         'ERI': 'Eritrea',
#         'EST': 'Estonia',
#         'ETH': 'Ethiopia',
#         'FJI': 'Fiji',
#         'FIN': 'Finland',
#         'FRA': 'France',
#         'GAB': 'Gabon',
#         'GMB': 'Gambia',
#         'GEO': 'Georgia',
#         'DEU': 'Germany',
#         'GHA': 'Ghana',
#         'GRC': 'Greece',
#         'GRD': 'Grenada',
#         'GTM': 'Guatemala',
#         'GIN': 'Guinea',
#         'GNB': 'Guinea-Bissau',
#         'GUY': 'Guyana',
#         'HTI': 'Haiti',
#         'HND': 'Honduras',
#         'HKG': 'Hong_Kong',
#         'HUN': 'Hungary',
#         'ISL': 'Iceland',
#         'IND': 'India',
#         'IDN': 'Indonesia',
#         'IRN': 'Iran',
#         'IRQ': 'Iraq',
#         'IRL': 'Ireland',
#         'ISR': 'Israel',
#         'ITA': 'Italy',
#         'JAM': 'Jamaica',
#         'JPN': 'Japan',
#         'JOR': 'Jordan',
#         'KAZ': 'Kazakhstan',
#         'KEN': 'Kenya',
#         'KIR': 'Kiribati',
#         'PRK': 'Dem._People’s_Rep._Korea',
#         'KOR': 'Rep._Korea',
#         'XKX': 'Kosovo',
#         'KWT': 'Kuwait',
#         'KGZ': 'Kyrgyz_Republic',
#         'LAO': 'Lao_PDR',
#         'LVA': 'Latvia',
#         'LBN': 'Lebanon',
#         'LSO': 'Lesotho',
#         'LBR': 'Liberia',
#         'LBY': 'Libya',
#         'LIE': 'Liechtenstein',
#         'LTU': 'Lithuania',
#         'LUX': 'Luxembourg',
#         'MAC': 'Macao',
#         'MKD': 'North_Macedonia',
#         'MDG': 'Madagascar',
#         'MWI': 'Malawi',
#         'MYS': 'Malaysia',
#         'MDV': 'Maldives',
#         'MLI': 'Mali',
#         'MLT': 'Malta',
#         'MHL': 'Marshall_Islands',
#         'MRT': 'Mauritania',
#         'MUS': 'Mauritius',
#         'MEX': 'Mexico',
#         'FSM': 'Micronesia',
#         'MDA': 'Moldova',
#         'MCO': 'Monaco',
#         'MNG': 'Mongolia',
#         'MNE': 'Montenegro',
#         'MAR': 'Morocco',
#         'MOZ': 'Mozambique',
#         'MMR': 'Myanmar',
#         'NAM': 'Namibia',
#         'NRU': 'Nauru',
#         'NPL': 'Nepal',
#         'NLD': 'Netherlands',
#         'NZL': 'New_Zealand',
#         'NIC': 'Nicaragua',
#         'NER': 'Niger',
#         'NGA': 'Nigeria',
#         'MNP': 'Northern_Mariana_Islands',
#         'NOR': 'Norway',
#         'OMN': 'Oman',
#         'PAK': 'Pakistan',
#         'PLW': 'Palau',
#         'PAN': 'Panama',
#         'PNG': 'Papua_New_Guinea',
#         'PRY': 'Paraguay',
#         'PER': 'Peru',
#         'PHL': 'Philippines',
#         'POL': 'Poland',
#         'PRT': 'Portugal',
#         'PRI': 'Puerto_Rico',
#         'QAT': 'Qatar',
#         'ROU': 'Romania',
#         'RUS': 'Russian_Federation',
#         'RWA': 'Rwanda',
#         'WSM': 'Samoa',
#         'SMR': 'San_Marino',
#         'STP': 'São_Tomé_and_Príncipe',
#         'SAU': 'Saudi_Arabia',
#         'SEN': 'Senegal',
#         'SRB': 'Serbia',
#         'SYC': 'Seychelles',
#         'SLE': 'Sierra_Leone',
#         'SGP': 'Singapore',
#         'SXM': 'Sint_Maarten',
#         'SVK': 'Slovak_Republic',
#         'SVN': 'Slovenia',
#         'SLB': 'Solomon_Islands',
#         'SOM': 'Somalia',
#         'ZAF': 'South_Africa',
#         'SSD': 'South_Sudan',
#         'ESP': 'Spain',
#         'LKA': 'Sri_Lanka',
#         'KNA': 'St._Kitts_and_Nevis',
#         'LCA': 'St._Lucia',
#         'MAF': 'St._Martin',
#         'VCT': 'Vincent_and_the_Grenadines',
#         'SDN': 'Sudan',
#         'SUR': 'Suriname',
#         'SWE': 'Sweden',
#         'CHE': 'Switzerland',
#         'SYR': 'Syrian_Arab_Republic',
#         'TWN': 'Taiwan',
#         'TJK': 'Tajikistan',
#         'TZA': 'Tanzania',
#         'THA': 'Thailand',
#         'TLS': 'Timor-Leste',
#         'TGO': 'Togo',
#         'TON': 'Tonga',
#         'TTO': 'Trinidad_and_Tobago',
#         'TUN': 'Tunisia',
#         'TUR': 'Turkey',
#         'TKM': 'Turkmenistan',
#         'TCA': 'Turks_and_Caicos_Islands',
#         'TUV': 'Tuvalu',
#         'UGA': 'Uganda',
#         'UKR': 'Ukraine',
#         'ARE': 'United_Arab_Emirates',
#         'GBR': 'United_Kingdom',
#         'USA': 'United_States',
#         'URY': 'Uruguay',
#         'UZB': 'Uzbekistan',
#         'VUT': 'Vanuatu',
#         'VEN': 'Venezuela',
#         'VNM': 'Vietnam',
#         'VIR': 'Virgin_Islands',
#         'PSE': 'West_Bank_and_Gaza',
#         'YEM': 'Yemen',
#         'ZMB': 'Zambia',
#         'ZWE': 'Zimbabwe'
#     }
    
#     return region_dict










